#!/bin/bash
set -e

# always use platform linux for glsl
# ./libs/bgfx/shaderc/shaderc-linux64 -f "srcPath" -o "outPath" --debug --disasm --verbose --Werror --type f --platform linux --varyingdef "varyingSrcPath" -i Natives/tools/bgfx/common
# ./libs/bgfx/shaderc/shaderc-linux64 -f "srcPath" -o "outPath" --debug --disasm --verbose --Werror --type v --platform linux --varyingdef "varyingSrcPath" -i Natives/tools/bgfx/common

cd shaders/src
cd ../..

rm -r shaders/bin
mkdir -p shaders/bin/glsl

# hmm... '--platform asm.js' output seems identical to '--platform linux' output
#mkdir -p shaders/bin/webgl

rm -r shaders/tmp
mkdir -p shaders/tmp

luajit shaders/unscx.lua shaders/src/texcolor.scx
./Natives/tools/bgfx/shaderc-linux64 -f "shaders/tmp/texcolor.vs.sc" -o "shaders/bin/glsl/texcolor.scx.vshader" --verbose --Werror --type v --platform linux --varyingdef "shaders/tmp/texcolor.varying.sc" -i Natives/tools/bgfx/common
./Natives/tools/bgfx/shaderc-linux64 -f "shaders/tmp/texcolor.fs.sc" -o "shaders/bin/glsl/texcolor.scx.fshader" --verbose --Werror --type f --platform linux --varyingdef "shaders/tmp/texcolor.varying.sc" -i Natives/tools/bgfx/common

luajit shaders/unscx.lua shaders/src/font.scx
./Natives/tools/bgfx/shaderc-linux64 -f "shaders/tmp/font.vs.sc" -o "shaders/bin/glsl/font.scx.vshader" --verbose --Werror --type v --platform linux --varyingdef "shaders/tmp/font.varying.sc" -i Natives/tools/bgfx/common
./Natives/tools/bgfx/shaderc-linux64 -f "shaders/tmp/font.fs.sc" -o "shaders/bin/glsl/font.scx.fshader" --verbose --Werror --type f --platform linux --varyingdef "shaders/tmp/font.varying.sc" -i Natives/tools/bgfx/common


luajit shaders/unscx.lua shaders/src/color.scx
./Natives/tools/bgfx/shaderc-linux64 -f "shaders/tmp/color.vs.sc" -o "shaders/bin/glsl/color.scx.vshader" --verbose --Werror --type v --platform linux --varyingdef "shaders/tmp/color.varying.sc" -i Natives/tools/bgfx/common
./Natives/tools/bgfx/shaderc-linux64 -f "shaders/tmp/color.fs.sc" -o "shaders/bin/glsl/color.scx.fshader" --verbose --Werror --type f --platform linux --varyingdef "shaders/tmp/color.varying.sc" -i Natives/tools/bgfx/common
