#!/bin/bash
set -e

# always use platform linux for glsl
# ./libs/bgfx/shaderc/shaderc-linux64 -f "srcPath" -o "outPath" --debug --disasm --verbose --Werror --type f --platform linux --varyingdef "varyingSrcPath" -i libs/bgfx/shaderc/common
# ./libs/bgfx/shaderc/shaderc-linux64 -f "srcPath" -o "outPath" --debug --disasm --verbose --Werror --type v --platform linux --varyingdef "varyingSrcPath" -i libs/bgfx/shaderc/common

cd shaders/src
cd ../..

mkdir -p shaders/bin/glsl
# hmm... '--platform asm.js' output seems identical to '--platform linux' output
#mkdir -p shaders/bin/webgl

mkdir -p shaders/tmp

luajit shaders/unscx.lua shaders/src/simple.scx
./Native/tools/bgfx/shaderc-linux64 -f "shaders/tmp/simple.vs.sc" -o "shaders/bin/glsl/simple.vs.bin" --verbose --Werror --type v --platform linux --varyingdef "shaders/tmp/simple.varying.sc" -i libs/bgfx/shaderc/common
./Native/tools/bgfx/shaderc-linux64 -f "shaders/tmp/simple.fs.sc" -o "shaders/bin/glsl/simple.fs.bin" --verbose --Werror --type f --platform linux --varyingdef "shaders/tmp/simple.varying.sc" -i libs/bgfx/shaderc/common

luajit shaders/unscx.lua shaders/src/font.scx
./Native/tools/bgfx/shaderc-linux64 -f "shaders/tmp/font.vs.sc" -o "shaders/bin/glsl/font.vs.bin" --verbose --Werror --type v --platform linux --varyingdef "shaders/tmp/font.varying.sc" -i libs/bgfx/shaderc/common
./Native/tools/bgfx/shaderc-linux64 -f "shaders/tmp/font.fs.sc" -o "shaders/bin/glsl/font.fs.bin" --verbose --Werror --type f --platform linux --varyingdef "shaders/tmp/font.varying.sc" -i libs/bgfx/shaderc/common
